---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is a large single nuclei RNA-seq dataset generated by Evangelyn Sim and Enzo Porrello from the Heart Regeneration group at the Murdoch Children’s Research Institute (MCRI). The samples were prepared by Evangelyn Sim and the data was processed and sequenced at the Translational Genomics Unit at MCRI.

This analysis will focus on data generated from the left ventricle from three groups: fetal (n=3), non-diseased (n=3), and DCM (n=4). There are several aspects of the analysis:

* Define the cell types present at each group.
* Analyse differences in cell type composition across these groups.
* Identify transcriptional pathways perturbed in DCM.
* Define fetal gene program in dilated cardiomyopathy.

Also, we have developed an interactive website that permits interrogation of our data set and, hence, increases the data set’s accessibility and utility. To check our website, please visit the [Heart Explorer](https://nedamcri.shinyapps.io/heartexplorerapp/).

